# Generated by Django 4.2.6 on 2024-01-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='safe_mode',
            field=models.CharField(choices=[('Enabled', 'Enabled'), ('Disabled', 'Disabled')], default='Disabled', max_length=10),
            preserve_default=False,
        ),
    ]
