# Generated by Django 4.2.6 on 2024-01-11 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='Unit_6_Matthew_Micah_Caleb_Conner/app/static/images/dinosaur_profile_default.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
